[phases.setup]
nixPkgs = ["php82", "nodejs"]

[phases.install]
cmds = [
    "npm ci --legacy-peer-deps",
    "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
    "npm run build",
    "cp -f public/build/.vite/manifest.json public/build/manifest.json",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
